exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 16
  num_workers: 0
dataset:
  name: MELD
  data_path: data/newFeatures/meld/audio_no_finetune.pkl
  noValid: false
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 20
  mode: max
lr_scheduler:
  active: false
  decay_rate: 0.9
model:
  name: CausalContextModel
  used_focal_loss: false
  loss_weight:
    - 0.002487 #1/402
    - 0.004808 #1/208
    - 0.000796 #1/1256
    - 0.002899 #1/345
    - 0.003559 #1/281
    - 0.02 #1/50
    - 0.014706 #1/68
  classes_name:
  - joy 
  - sadness 
  - neutral 
  - anger 
  - surprise 
  - fear 
  - disgust
  adapter:
    projector_dim: 768
    select: DeepModel
    UtteranceLevel:
      pooling: MeanPooling
    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 512
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.7
    output_dim: 256
  causalGNN:
    name: CausalGAT
    gfn: false
    dropout: 0.3
    edge_norm: false
    context_before: 2
    context_after: 2
    args:
      global_pool_type: sum
      with_keypoints: true
      use_residual: true
      layers: 2
      hidden: 256
      with_random: true
      eval_random: true
      without_node_attention: false
      without_edge_attention: false
      fc_num: 222
      cat_or_add: cat
      c: 0.5
      o: 1.0
      co: 0.5
  uttr_input_dim: 1024
optimizer:
  learning_rate: 0.0001
  type: Adam
  weight_decay: 0.000
seed: 100
trainer:
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0