exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 16
  num_workers: 0
dataset:
  name: MELD
  data_path: data/newFeatures/meld/audio_no_finetune.pkl
  cross_val: 1
  noValid: true
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 50
  mode: max
lr_scheduler:
  active: false
  decay_rate: 0.9
model:
  name: CausalLocalConcatDiaModel
  uttr_input_dim: 1024
  classes_name:
  - joy
  - sadness
  - neutral
  - anger
  - surprise
  - fear
  - disgust
  used_focal_loss: false
  adapter:
    projector_dim: 768
    select: DeepModel
    UtteranceLevel:
      pooling: MeanPooling
    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 512
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.7
    output_dim: 256
  causalGNN:
    name: CausalGAT
    gfn: false
    dropout: 0.3
    edge_norm: false
    context_before: 2
    context_after: 2
    args:
      with_keypoints: true
      use_residual: true
      layers: 2
      hidden: 256
      with_random: true
      eval_random: true
      without_node_attention: false
      without_edge_attention: false
      fc_num: 222
      cat_or_add: cat
      c: 0.5
      o: 1.0
      co: 0.5
      global_pool_type: sum
  dialogModel:
    name: ADGCNForDialog
    to_future_link: 10
    to_past_link: 10
    hidden_size: 100
    layers: 10
    dropout: 0.6
    head_num: 3
    alpha: 0.1
    theta: 0.5
    out_size: 256
  featureFusion:
    type: PureConcat
    cross_attention_heads: 4
    hidden: 256
    dropout: 0.3
optimizer:
  learning_rate: 0.0001
  type: Adam
  weight_decay: 0.0
seed: 100
trainer:
  gpus:
  - 0
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0