exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 2
  num_workers: 0
dataset:
  name: MELD
  data_path: data/newFeatures/meld/audio_no_finetune.pkl
  noValid: true
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 20
  mode: max
lr_scheduler:
  active: false
  decay_rate: 0.9
model:
  loss_weight:
    - 0.002487
    - 0.004808
    - 0.000796
    - 0.002899
    - 0.003559
    - 0.02
    - 0.014706
  adapter:
    projector_dim: 768
    select: DeepModel
    UtteranceLevel:
      pooling: MeanPooling
    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 512
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.4
    output_dim: 256
  dialogModel:
    # base_model: LSTM
    D_m: null    # input_size
    D_g: 256    # only dialogRnn
    D_p: 256    # only dialogRnn
    D_e: 256    # hidden_size
    D_h: 256   # unused
    D_a: 256   # unused
    # graph_hidden_size: 100 
    n_speakers: 9
    max_seq_len: 110 
    window_past: 10
    window_future: 10
    dropout_rec: 0.5 # only dialogRnn
    dropout: 0.5
    nodal_attention: True
    avec: False
  uttr_input_dim: 1024
  classes_name:
  - joy 
  - sadness 
  - neutral 
  - anger 
  - surprise 
  - fear 
  - disgust
optimizer:
  learning_rate: 0.001
  type: Adam
  weight_decay: 0
seed: 100
trainer:
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0