exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 16
  num_workers: 0
dataset:
  name: MELD
  data_path: data/newFeatures/meld/audio.pkl
  noValid: True
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 20
  mode: max
lr_scheduler:
  active: false
  decay_rate: 0.9
model:
  # used_focal_loss: true
  loss_weight:
  - 0.002487 #1/402
  - 0.004808 #1/208
  - 0.000796 #1/1256
  - 0.002899 #1/345
  - 0.003559 #1/281
  - 0.02 #1/50
  - 0.014706 #1/68
  adapter:
    projector_dim: 768
    select: DeepModel
    UtteranceLevel:
      pooling: MeanPooling
    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 256
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.4
    output_dim: 256
  dialogModel:
    base_model: LSTM
    base_layer: 2
    input_size: None
    hidden_size: 256
    n_speakers: 9
    dropout: 0.5
    cuda_flag: True
    reason_steps: [3, 0]
  uttr_input_dim: 1024
  classes_name:
  - joy 
  - sadness 
  - neutral 
  - anger 
  - surprise 
  - fear 
  - disgust
optimizer:
  learning_rate: 0.0001
  type: Adam
  weight_decay: 0.0
seed: 100
trainer:
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0