exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 2
  num_workers: 0
dataset:
  name: IEMOCAP5531CrossValWithFrame
  data_path: data/featuresFromPretrain/wavlm_large_finetune_fold1_with_val_s3prl_full_mean_hidden.pkl
  cross_val: 1
  max_sentences: 120
  noValid: false
  # random_valid: 0.2
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 10
  mode: max
lr_scheduler:
  active: true
  decay_rate: 0.9
model:
  name: DiaModel
  adapter:
    projector_dim: 768
    select: DeepModel
    UtteranceLevel:
      pooling: MeanPooling
    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 256
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.4
    output_dim: 256
  dialogModel:
    name: ADGCNForDialog
    to_future_link: 2
    to_past_link: 2
    hidden_size: 256
    layers: 2
    dropout: 0.5
    head_num: 3
    alpha: 0.1
    theta: 0.5
    useDLR: true
    useAOR: false
  uttr_input_dim: 1024
  classes_name:
  - 'N'
  - A
  - S
  - H
optimizer:
  learning_rate: 0.00001
  type: Adam
  weight_decay: 0.0
seed: 0
trainer:
  gpus:
  - 0
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0