exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 16
  num_workers: 0
dataset:
  name: MELD
  data_path: data/newFeatures/meld/audio.pkl
  cross_val: 1
  noValid: false
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 20
  mode: max
lr_scheduler:
  active: false
  decay_rate: 0.9
model:
  name: DiaModel
  adapter:
    projector_dim: 768
    select: DeepModel
    UtteranceLevel:
      pooling: MeanPooling
    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 512
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.7
    output_dim: 256
  dialogModel:
    name: GCNForDialog
    to_future_link: 3
    to_past_link: 3
    hidden_size: 256
    layers: 10
    dropout: 0.5
    head_num: 3
    alpha: 0.1
    theta: 0.5
    residual: true
  uttr_input_dim: 1024
  classes_name:
  - joy
  - sadness
  - neutral
  - anger
  - surprise
  - fear
  - disgust
  used_focal_loss: false
optimizer:
  learning_rate: 0.0001
  type: Adam
  weight_decay: 0.0
seed: 100
trainer:
  gpus:
  - 0
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0