exp_mode: train
show_tsne: false
checkpoints:
  filename: '{epoch}-{val_loss:.5f}-{val_accuracy:.5f}'
  monitor: val_accuracy
  save_last: true
  save_on_train_epoch_end: false
  save_top_k: 10
  mode: max
data_loader:
  batch_size: 2
  num_workers: 0
dataset:
  name: MELD
  data_path: data/newFeatures/meld/audio.pkl
  cross_val: 1
  noValid: true
earlystop:
  monitor: val_accuracy
  check_on_train_epoch_end: false
  patience: 10
  mode: max
lr_scheduler:
  active: true
  type: CosineAnnealingWarmRestarts
  params: 
    T_0: 3
    T_mult: 2
    eta_min: 0.00001
model:
  uttr_input_dim: 1024
  loss_weight:
    - 0.002487
    - 0.004808
    - 0.000796
    - 0.002899
    - 0.003559
    - 0.02
    - 0.014706
  classes_name:
  - joy 
  - sadness 
  - neutral 
  - anger 
  - surprise 
  - fear 
  - disgust
  dwFormer:
    FFNdim: 512
    n_head: 8
optimizer:
  learning_rate: 0.0005
  type: SGD
  weight_decay: 0.0005
seed: 100
trainer:
  gpus:
  - 0
  log_every_n_steps: 1
  max_epochs: 500
  accelerator: gpu
  devices:
  - 0